[build]
  command = "npm install"
  functions = "functions"
  publish = "."  # Changed from "public" to current directory

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  targetPort = 8888
  autoLaunch = false